# Generated by Django 4.2.11 on 2024-03-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('graduation_year', models.IntegerField()),
                ('university', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField()),
                ('video', models.FileField(upload_to='')),
            ],
        ),
    ]
