# Generated by Django 4.2.11 on 2024-04-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_created_at_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hello this is my bio', max_length=300),
            preserve_default=False,
        ),
    ]
