# Generated by Django 4.2.11 on 2024-05-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='default.jpeg', upload_to=''),
            preserve_default=False,
        ),
    ]
